/* tslint:disable */
/* eslint-disable */
/**
 * Tavern Profile Api
 * The Tavern-Profile-API is a backend application meant to geve access to users, see other profiles, and like or dislike profiles.
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Character,
    CharacterFromJSON,
    CharacterFromJSONTyped,
    CharacterToJSON,
} from './Character';

/**
 * 
 * @export
 * @interface CharacterDetailedResponse
 */
export interface CharacterDetailedResponse {
    /**
     * 
     * @type {Character}
     * @memberof CharacterDetailedResponse
     */
    data?: Character;
    /**
     * 
     * @type {boolean}
     * @memberof CharacterDetailedResponse
     */
    succsessful?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CharacterDetailedResponse
     */
    message?: string;
}

export function CharacterDetailedResponseFromJSON(json: any): CharacterDetailedResponse {
    return CharacterDetailedResponseFromJSONTyped(json, false);
}

export function CharacterDetailedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharacterDetailedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : json['data'],
        'succsessful': !exists(json, 'succsessful') ? undefined : json['succsessful'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function CharacterDetailedResponseToJSON(value?: CharacterDetailedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
        'succsessful': value.succsessful,
        'message': value.message,
    };
}

