/* tslint:disable */
/* eslint-disable */
/**
 * Tavern Profile Api
 * The Tavern-Profile-API is a backend application meant to geve access to users, see other profiles, and like or dislike profiles.
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Plot
 */
export interface Plot {
    /**
     * 
     * @type {string}
     * @memberof Plot
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Plot
     */
    plotName?: string;
    /**
     * 
     * @type {string}
     * @memberof Plot
     */
    plot?: string;
}

export function PlotFromJSON(json: any): Plot {
    return PlotFromJSONTyped(json, false);
}

export function PlotFromJSONTyped(json: any, ignoreDiscriminator: boolean): Plot {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'plotName': !exists(json, 'plot_name') ? undefined : json['plot_name'],
        'plot': !exists(json, 'plot') ? undefined : json['plot'],
    };
}

export function PlotToJSON(value?: Plot | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'plot_name': value.plotName,
        'plot': value.plot,
    };
}

