/* tslint:disable */
/* eslint-disable */
/**
 * Tavern Profile Api
 * The Tavern-Profile-API is a backend application meant to geve access to users, see other profiles, and like or dislike profiles.
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Plot,
    PlotFromJSON,
    PlotFromJSONTyped,
    PlotToJSON,
} from './Plot';

/**
 * 
 * @export
 * @interface PlotDetailedResponse
 */
export interface PlotDetailedResponse {
    /**
     * 
     * @type {Plot}
     * @memberof PlotDetailedResponse
     */
    data?: Plot;
    /**
     * 
     * @type {boolean}
     * @memberof PlotDetailedResponse
     */
    succsessful?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PlotDetailedResponse
     */
    message?: string;
}

export function PlotDetailedResponseFromJSON(json: any): PlotDetailedResponse {
    return PlotDetailedResponseFromJSONTyped(json, false);
}

export function PlotDetailedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlotDetailedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : json['data'],
        'succsessful': !exists(json, 'succsessful') ? undefined : json['succsessful'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function PlotDetailedResponseToJSON(value?: PlotDetailedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
        'succsessful': value.succsessful,
        'message': value.message,
    };
}

