/* tslint:disable */
/* eslint-disable */
/**
 * Tavern Profile Api
 * The Tavern-Profile-API is a backend application meant to geve access to users, see other profiles, and like or dislike profiles.
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface UsersDetailedResponse
 */
export interface UsersDetailedResponse {
    /**
     * 
     * @type {Array<User>}
     * @memberof UsersDetailedResponse
     */
    data?: Array<User> | null;
    /**
     * 
     * @type {boolean}
     * @memberof UsersDetailedResponse
     */
    succsessful?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UsersDetailedResponse
     */
    message?: string;
}

export function UsersDetailedResponseFromJSON(json: any): UsersDetailedResponse {
    return UsersDetailedResponseFromJSONTyped(json, false);
}

export function UsersDetailedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersDetailedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(UserFromJSON)),
        'succsessful': !exists(json, 'succsessful') ? undefined : json['succsessful'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function UsersDetailedResponseToJSON(value?: UsersDetailedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(UserToJSON)),
        'succsessful': value.succsessful,
        'message': value.message,
    };
}

