/* tslint:disable */
/* eslint-disable */
/**
 * Tavern Profile Api
 * The Tavern-Profile-API is a backend application meant to geve access to users, see other profiles, and like or dislike profiles.
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface UserDetailedResponse
 */
export interface UserDetailedResponse {
    /**
     * 
     * @type {User}
     * @memberof UserDetailedResponse
     */
    data?: User;
    /**
     * 
     * @type {boolean}
     * @memberof UserDetailedResponse
     */
    succsessful?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserDetailedResponse
     */
    message?: string;
}

export function UserDetailedResponseFromJSON(json: any): UserDetailedResponse {
    return UserDetailedResponseFromJSONTyped(json, false);
}

export function UserDetailedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDetailedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : json['data'],
        'succsessful': !exists(json, 'succsessful') ? undefined : json['succsessful'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function UserDetailedResponseToJSON(value?: UserDetailedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
        'succsessful': value.succsessful,
        'message': value.message,
    };
}

